viaacode/hetarchief-proxy

package-lock.json
package.json
src/app.controller.ts
src/main.ts
src/modules/auth/controllers/auth.controller.ts
src/modules/auth/controllers/het-archief.controller.ts
src/modules/auth/controllers/meemoo.controller.ts
src/modules/data/controllers/data.controller.ts
src/modules/spaces/controllers/spaces.controller.ts
src/modules/spaces/dto/spaces.dto.ts

Enable swagger docs for all servers except production:
under the route:
http://localhost:3100/docs/

feat(swagger): enable swagger docs for non production servers

---

.env/.env.template
src/config/config.types.ts
src/config/index.ts
src/main.ts
src/modules/auth/controllers/auth.controller.ts
src/modules/auth/controllers/het-archief.controller.spec.ts
src/modules/auth/controllers/het-archief.controller.ts
src/modules/auth/controllers/meemoo.controller.spec.ts
src/modules/auth/controllers/meemoo.controller.ts
src/modules/auth/services/saml.service.ts
src/modules/data/services/data.service.ts

Missing environment variables that are required for the service to run, now throw error messages:
```
st] 8828  - 02/28/2022, 9:53:12 AM     LOG [NestFactory] Starting Nest application...
[Nest] 8828  - 02/28/2022, 9:53:12 AM   ERROR [ExceptionHandler] The environment variable TICKET_SERVICE_URL is not set, but is required to run the service.
NotImplementedException: The environment variable TICKET_SERVICE_URL is not set, but is required to run the service.
at getEnvValue (C:\Users\bert\Documents\studiohyperdrive\repos\hetarchief-proxy\src\config\index.ts:28:9)
at InstanceWrapper.config [as metatype] (C:\Users\bert\Documents\studiohyperdrive\repos\hetarchief-proxy\src\config\index.ts:72:21)
at Injector.instantiateClass (C:\Users\bert\Documents\studiohyperdrive\repos\hetarchief-proxy\node_m …
```

feat(arc-300): improve missing environment variable errors

---

src/app.module.ts
src/modules/notifications/controllers/notifications.controller.spec.ts
src/modules/notifications/controllers/notifications.controller.ts
src/modules/notifications/dto/notifications.dto.ts
src/modules/notifications/index.ts
src/modules/notifications/notifications.module.ts
src/modules/notifications/services/__mocks__/app_notification.ts
src/modules/notifications/services/notifications.service.spec.ts
src/modules/notifications/services/notifications.service.ts
src/modules/notifications/services/queries.gql.ts
src/modules/notifications/types.ts

Implements:
* https://meemoo.atlassian.net/browse/ARC-283
* https://meemoo.atlassian.net/browse/ARC-284
Creating a notification is only implemented in the service, since the proxy will be creating those notification in response to other api calls.

feat(arc-283): add routes for getting notifications and marking as read

---

src/modules/collections/services/collections.service.spec.ts
src/modules/notifications/controllers/notifications.controller.spec.ts
src/modules/notifications/services/notifications.service.spec.ts
src/modules/notifications/services/notifications.service.ts
src/modules/notifications/types.ts
src/modules/visits/controllers/visits.controller.spec.ts
src/modules/visits/controllers/visits.controller.ts
src/modules/visits/services/visits.service.spec.ts
src/modules/visits/services/visits.service.ts
src/modules/visits/types.ts

```
-------------------------------------------|---------|----------|---------|---------|----------------------------
File                                       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s          
-------------------------------------------|---------|----------|---------|---------|----------------------------
src/modules/notifications/controllers     |     100 |      100 |     100 |     100 |                           
notifications.controller.ts              |     100 |      100 |     100 |     100 |                           
src/modules/notifications/dto             |      80 |      100 |   33.33 |      75 |                           
notifications.dto.ts                     |      80 |      100 |   33.33 |      75 | 7,17 …
```

feat(arc-430): Move notification construction to notifications service

---

src/modules/admin/navigations/services/navigations.service.spec.ts
src/modules/auth/controllers/het-archief.controller.ts
src/modules/auth/controllers/meemoo.controller.ts
src/modules/collections/controllers/collections.controller.spec.ts
src/modules/notifications/controllers/notifications.controller.spec.ts
src/modules/notifications/services/notifications.service.spec.ts
src/modules/users/services/queries.gql.ts
src/modules/users/services/users.service.spec.ts
src/modules/users/services/users.service.ts
src/modules/users/types.ts
src/modules/visits/controllers/visits.controller.spec.ts
src/shared/auth/session-helper.spec.ts

return permissions in check-login
- Requires PR for Hasura: https://github.com/viaacode/hetarchief-hasura/pull/67
- Assumes the user.profile is linked to a (user)group in the DB

feat(arc-535): add permissions for user model

---

src/modules/collections/controllers/collections.controller.spec.ts
src/modules/collections/controllers/collections.controller.ts
src/modules/collections/services/__mocks__/users_collection.ts
src/modules/collections/services/collections.service.spec.ts
src/modules/collections/services/collections.service.ts
src/modules/collections/services/queries.gql.ts
src/modules/collections/types.ts
src/modules/media/services/media.service.ts
src/modules/media/services/queries.gql.ts
src/modules/media/types.ts

When you add an object to a collection the client will pass the schema_identifier id
the backend will resolve this id to the meemoo_fragment_id
and then insert the collection_ie object with both ids
Still some issues where elasticsearch contains items that do not seem to be present in the postgres database.

fix(collections): fix issue with schema identifier vs meemoo fragment id

---

src/modules/visits/controllers/visits.controller.spec.ts
src/modules/visits/controllers/visits.controller.ts
src/modules/visits/services/visits.service.spec.ts
src/modules/visits/services/visits.service.ts

add endpoint to get the active visit for the logged in user in the given space
UPDATED ROUTE:  /visits/active-for-space/:spaceId

feat(arc-486): get active visit for user and space

---

src/modules/admin/navigations/services/navigations.service.spec.ts
src/modules/collections/controllers/collections.controller.spec.ts
src/modules/notifications/controllers/notifications.controller.spec.ts
src/modules/notifications/services/notifications.service.spec.ts
src/modules/users/services/queries.gql.ts
src/modules/users/services/users.service.ts
src/modules/users/types.ts
src/modules/visits/controllers/visits.controller.spec.ts
src/shared/auth/session-helper.spec.ts

https://meemoo.atlassian.net/browse/ARC-184
still todo:
* ensure fresh user data is fetched from ldap after the user updates his info in on the ssum page
* check if "change password" button should also be shown?
Hetarchief idp users can see the "edit profile settings" button:
It redirect to the ssum edit page:
And after saving your changes it redirect back to the profile page:

feat(arc-184): add idp to user info and check-login response

---

src/modules/admin/navigations/services/navigations.service.spec.ts
src/modules/auth/controllers/het-archief.controller.ts
src/modules/collections/controllers/collections.controller.spec.ts
src/modules/notifications/controllers/notifications.controller.spec.ts
src/modules/notifications/services/notifications.service.spec.ts
src/modules/spaces/controllers/spaces.controller.spec.ts
src/modules/spaces/controllers/spaces.controller.ts
src/modules/spaces/services/queries.gql.ts
src/modules/spaces/services/spaces.service.spec.ts
src/modules/spaces/services/spaces.service.ts
src/modules/users/types.ts
src/modules/visits/controllers/visits.controller.spec.ts
src/modules/visits/controllers/visits.controller.ts
src/modules/visits/dto/visits.dto.ts
src/modules/visits/services/visits.service.spec.ts
src/modules/visits/services/visits.service.ts
src/shared/auth/session-helper.spec.ts
src/shared/auth/session-helper.ts
src/shared/decorators/user.decorator.ts

https://meemoo.atlassian.net/browse/ARC-592
* check permissions based on logged in user
* add mock permissions array for the hetarchief idp
* add @SessionUser decorator for easy access to user object
* add service function to get space by cpAdmin profile id
* avoid throwing exceptions in services for not found cases. So we can reuse the service functions for other purposes
* removed filter option for userProfileId => we'll use the session user id
* remove filter option for spaceId => we'll use the space that is linked to the current session user

feat(arc-592): change visits route to allow cp-admins and meemoo-admins

---

src/modules/auth/controllers/het-archief.controller.ts
src/shared/auth/session-helper.ts

otherwise you can get into this scenario:
* re-seed the database
* login to the app (your session gets a list of permissions)
* make a visit request
* go to cp admin visit requests
* you need to accept the tos first
* accept tos
* during the update call, a new user object is set on the session, overwriting the earlier fake list
* visits call fails, because you do not have permissions

fix(session-helper): ensure fake permissions are not reset on tos accept

---

src/modules/collections/services/collections.service.ts

Metadata shown for collection item in FE:
maintainerName
series
programs
format
dateCreatedLowerBound
datePublished
meemooIdentifier
schemaIdentifier
- series & programs: not queryable using freetext since stored as jsonb in DB
- dateCreatedLowerBound en datePublished  not queryable using freetext since they require an exact date format

feat(arc-288): update freetext search in collection objects

---

src/modules/collections/controllers/collections.controller.spec.ts
src/modules/collections/controllers/collections.controller.ts
src/modules/events/controllers/events.controller.spec.ts
src/modules/events/controllers/events.controller.ts
src/modules/events/dto/events.dto.ts
src/modules/events/types.ts
src/modules/media/controllers/media.controller.spec.ts
src/modules/media/controllers/media.controller.ts
src/modules/media/media.module.ts

* Add data and path options to the POST /events route
* trigger the metadata export event during export metadata for object and collection

feat(arc-769): Add data and path, trigger metadata export events

---

src/modules/events/services/events.service.ts

Currently we don't get enough info to debug an issue with inserted events:

feat(events): improve logging errors during logging events

---

src/modules/collections/dto/collections.dto.spec.ts
src/modules/collections/dto/collections.dto.ts
src/modules/collections/services/collections.service.ts

Related PR: https://github.com/viaacode/hetarchief-client/pull/312
This avoids queries like this:
```json
{
"collectionId": "c76d3cbc-6743-428b-b74c-e682f6c7ceee",
"userProfileId": "bee33872-2823-42a4-a619-2089ae145af3",
"where": {
"_or": [
{
"ie": {
"schema_name": {
"_ilike": "%%"
}
}
},
{
"ie": {
"maintainer": {
"schema_name": {
"_ilike": "%%"
}
}
}
},
{
"ie": {
"dcterms_format": {
"_ilike": "%%"
}
}
},
{
"ie": {
"meemoo_identifier": {
"_ilike": "%%"
}
}
},
{
"ie": {
"schema_identifier": {
"_ilike": "%%"
}
}
}
]
},
"offset": 0,
"limit": 20
}
```

fix(arc-213): Only add where object if query is defined

---

Dockerfile

dist folder structure changed after package.json (outside the src folder) was required in the status module

Fix docker deploy

---

src/modules/admin/content-pages/controllers/content-pages.controller.ts
src/modules/admin/content-pages/dto/content-pages.dto.ts
src/modules/admin/content-pages/services/content-pages.service.ts

* The route itself wasn't correcte migrated from avo to hetarchief
* paging is anders
* user groups are now strings
required to get the admin-core to work for testing:

fix(arc-611): Fix issues with content page overview route

---

src/modules/admin/content-pages/controllers/content-pages.controller.ts

A content page should be published before you can retrieve it, unless you're the owner of the page

fix(arc-858): check publish state for content page exists route

---

src/modules/media/elasticsearch/queryBuilder.spec.ts
src/modules/media/elasticsearch/queryBuilder.ts

https://meemoo.atlassian.net/browse/ARC-957
before: (linked to prod elasticsearch)
after: (linked to prod elasticsearch)

fix(arc-957): text search should only match with one strategy, not all

---

src/modules/organisations/services/organisations.service.ts

the latest version of hasura complains about
expected value of type jsonb
but some organisations have logo: null

fix(hasura): fix organisation caching for orgs without a logo

---

src/generated/graphql-db-types-hetarchief.ts
src/modules/visits/queries/delete-visit-folder-access.graphql
src/modules/visits/queries/find-visit-folder-access.graphql
src/modules/visits/services/visits.service.spec.ts
src/modules/visits/services/visits.service.ts

Issue
- During patch phase it would everytime create new entries in the folder access table. However that would cause side effect of returning more folderIds than there should be
Solution
- Check if accessType is FOLDERS with folderIds or accessType FULL -> delete existing folder access 
- For accessType is FOLDERS with folderIds insert the new access folder ids.

fix(visit-folder-access): delete folder access for update and full

---

jest.config.js
package.json

reduces test execution time from 88 seconds to 28 seconds

fix(test): improve jest execution speed on windows

---

src/modules/ie-objects/dto/ie-objects.dto.ts
src/modules/ie-objects/elasticsearch/elasticsearch.consts.ts
src/modules/ie-objects/elasticsearch/queryBuilder.spec.ts
src/modules/ie-objects/elasticsearch/queryBuilder.ts
src/modules/ie-objects/helpers/check-and-fix-format-filter.spec.ts
src/modules/ie-objects/helpers/convert-node-to-es-query-filter-objects.spec.ts
src/modules/ie-objects/helpers/convert-node-to-es-query-filter-objects.ts
src/modules/ie-objects/services/ie-objects.service.spec.ts
src/modules/ie-objects/services/ie-objects.service.ts

https://meemoo.atlassian.net/browse/ARC-1604
Requires client pr: https://github.com/viaacode/hetarchief-client/pull/783
🔴🔴🔴  Needs to be merged at the same time as the client or search will break
* Fixes some issues with the search:
* Fixed issue with fuzzy search
* Fixed issue with consultableRemote
* Renamed consultableRemote to ConsultableOnlyOnLocation to get rid of the inverted filter, since it was causing the filter handing in the backend to be more difficult
* Added tests in the backend for checking fuzzy search, exact search, consultableOnlyOnLocation and consultableMedia
* Allow no filter to be passed for consultableOnlyOnLocation => means no filter was enabled
before:
after:

fix(arc-1604): fix text search and consultable filters + add tests

---

src/app.module.ts
src/modules/campaign-monitor/dto/campaign-monitor.dto.ts
src/modules/campaign-monitor/mocks/campaign-monitor.mocks.ts
src/modules/campaign-monitor/services/campaign-monitor.service.spec.ts
src/modules/campaign-monitor/services/campaign-monitor.service.ts

https://meemoo.atlassian.net/browse/ARC-1541
* Use bulk import endpoint to avoid 429 rate limit errors
* Fix checking for subscribed to newsletter through custom field
* Don't clear values, but set them to be empty
The switch between on and off happens after 15 seconds in campaign monitor. So reloading the page after 15 seconds should reflect the change you made.

fix(arc-1541): switch CM to bulk endpoint, fix newsletter check

---

src/modules/spaces/controllers/spaces.controller.spec.ts
src/modules/spaces/controllers/spaces.controller.ts

https://meemoo.atlassian.net/browse/ARC-1612
example url: http://localhost:3200/admin/bezoekersruimtesbeheer/bezoekersruimtes/bruzzel
before:
after:

fix(arc-1612): allow meemoo admin to get inactive visitor space info

---

src/modules/visits/controllers/visits.controller.ts

https://meemoo.atlassian.net/browse/ARC-1659
The objects in the ticket are only on QAS, not on TST, so we can't really test this. 
There will also a FE PR for this ticket: https://github.com/viaacode/hetarchief-client/pull/877

fix(arc-1659): throw notFound error when meemoo admin finds no space

---

src/modules/auth/controllers/het-archief.controller.ts

https://meemoo.atlassian.net/browse/ARC-1536
prefer the OR-ids over the school ids, when filling in the organisation of a user from their ldap o (organisation) attribute
In the future we'll want to apply the same fix as for avo where we can identify schools vs organisations based on the organisation api cache

fix(arc-1536): prefer-or-ids over school ids from ldap info

---

src/modules/ie-objects/elasticsearch/elasticsearch.consts.ts

https://meemoo.atlassian.net/browse/ARC-1655
Add a filter option to only receive search result objects that have specific licenses
So we can show only objects with the BEZOEKRERTOOL license on the search page if a user selected a visitor space
```json
{
"size": 39,
"from": 0,
"query": {
"bool": {
"should": [
{
"bool": {
"filter": [],
"must": [
{
"term": {
"schema_maintainer.schema_identifier": "OR-7h1dk9t"
}
},
{
"terms": {
"schema_license": [
"BEZOEKERTOOL-METADATA-ALL",
"BEZOEKERTOOL-CONTENT"
]
}
}
]
}
},
```
before:
after:

fix(1655): add license filter to filter on objects with bzt license

---

src/modules/ie-objects/ie-objects.conts.ts

https://meemoo.atlassian.net/browse/ARC-1696
Thought process: If a user is allowed to see all the Intra cp metadata, he should also be allowed to see the limited intra cp metadata. Because the limited metadata is included in all the metadata.
Before: logged in as user.OR-sf2mb2h@meemoo.be: 
After: logged in as user.OR-sf2mb2h@meemoo.be:

fix(arc-1696): add insta cp metadata limited to matrix

---

src/modules/ie-objects/services/ie-objects.service.ts

https://meemoo.atlassian.net/browse/ARC-1708
Those objects accessthrough now have the sector, the screen is now displaying a different error message but that is supposed to be fixed in ARC-1740.

fix(arc-1708): get sector from object itself

---

src/modules/ie-objects/elasticsearch/queryBuilder.ts

https://meemoo.atlassian.net/browse/ARC-1768
And not to basic users that have key rights and are linked to an organization
test account: hetarchief2.0+autsleutelvrt@meemoo.be
test page: http://localhost:3200/zoeken?aanbieder=&format=all&orderDirection=desc&orderProp=relevance&page=2
before:
after:

fix(arc-1768): show visitor space objects only to cp admin and kiosk

---

src/modules/material-requests/controllers/material-requests.controller.spec.ts
src/modules/material-requests/controllers/material-requests.controller.ts
src/modules/material-requests/material-requests.module.ts

https://meemoo.atlassian.net/browse/ARC-1799
We were triggering events for material requests from the client that go through the external form url for VRT and UGent, but we had forgotten to trigger the events for the regular material requests when they are sent through the backend.

fix(arc-1799): trigger events when material requests are sent out

---

src/modules/users/services/users.service.ts

fix(ARC-2029): store idp uuid in correct column for new users

---

src/modules/users/services/users.service.ts

https://meemoo.atlassian.net/browse/ARC-2028
logging in with a new kiosk user now shows the correct content and visitor space:

fix(ARC-2028): correctly link new users to their organisation

---

src/modules/ie-objects/elasticsearch/queryBuilder.ts
src/modules/ie-objects/services/ie-objects.service.ts

https://meemoo.atlassian.net/browse/ARC-2521
also improve error logging for ie objects endpoint
before:
after:

fix(ARC-2521): do not read all/limited prop for name advanced filters

---

src/modules/material-requests/controllers/material-requests.controller.ts
src/modules/material-requests/material-requests.types.ts

https://github.com/viaacode/hetarchief-client/pull/1259
since this is already mapped in the adapt function, we no longer need to map it during material request sending
client PR: https://github.com/viaacode/hetarchief-client/pull/1259

fix(ARC-2511): use maintainer contact email directly
