- Dockerfile
- openshift/Jenkinsfile
- openshift/Makefile
Add the Jenkinsfile and used Makefile.
> ARC-338 Create Jenkins pipeline

- Dockerfile
- tsconfig.build.json
Fixed Dockerfile path to main.js
> fix: point to src/main.js in dockerfile

- .env/.env.template
- src/config/config.const.ts
- src/config/config.types.ts
- src/config/index.ts
- src/modules/auth/auth.module.ts
- src/modules/auth/controllers/het-archief.controller.spec.ts
- src/modules/auth/controllers/meemoo.controller.spec.ts
- src/modules/auth/controllers/meemoo.controller.ts
- src/modules/auth/services/het-archief.service.ts
- src/modules/auth/services/meemoo.service.ts
- src/modules/auth/services/saml.service.ts
- src/modules/auth/types.ts
Created abstract SamlService with common logic. Extended by both the MeemooService and HetArchiefService
> ARC-272 Implement meemoo IDP

- .env/.env.template
- README.md
- src/config/config.const.ts
- src/modules/auth/auth.module.ts
- src/modules/auth/controllers/auth.controller.spec.ts
- src/modules/auth/controllers/auth.controller.ts
- src/modules/auth/controllers/het-archief.controller.spec.ts
- src/modules/auth/controllers/het-archief.controller.ts
- src/modules/auth/types.ts
- src/modules/data/data.module.ts
- src/modules/data/services/data.service.ts
- src/modules/users/dto/users.dto.ts
- src/modules/users/index.ts
- src/modules/users/services/queries.gql.ts
- src/modules/users/services/users.service.spec.ts
- src/modules/users/services/users.service.ts
- src/modules/users/types.ts
- src/modules/users/user.module.ts
Adds logic to query user, and create/update user on login if necessary
> feat(archiefidp): add user module and user service

- src/modules/auth/controllers/meemoo.controller.spec.ts
- src/modules/auth/controllers/meemoo.controller.ts
- src/modules/auth/types.ts
based on PR #11, adds user logic to Meemoo controller
> feat(arc-272): add user logic to meemoo controller

- .env/.env.template
- src/config/config.const.ts
- src/config/config.types.ts
- src/config/index.ts
- src/modules/auth/controllers/het-archief.controller.spec.ts
- src/modules/auth/controllers/het-archief.controller.ts
- src/modules/auth/controllers/meemoo.controller.spec.ts
- src/modules/auth/controllers/meemoo.controller.ts
- src/modules/auth/services/meemoo.service.ts
- src/modules/auth/services/saml.service.ts
Env vars update
set saml settings based on certificate
> refactor(arc-396): updated env vars

- src/config/config.const.ts
- src/modules/auth/controllers/auth.controller.ts
- src/shared/services/session.service.ts
> feat(logging): add logging and debug call

- src/modules/auth/controllers/auth.controller.ts
- src/modules/auth/controllers/het-archief.controller.ts
- src/modules/auth/controllers/meemoo.controller.ts
- src/modules/auth/services/het-archief.service.ts
- src/modules/auth/services/meemoo.service.ts
- src/modules/auth/services/saml.service.ts
- src/modules/data/services/data-permissions.service.ts
- src/modules/users/services/users.service.ts
Idp logging toegevoegd
logger initialisatie consistent gemaakt
> feat(logging): update logging

- src/modules/auth/controllers/meemoo.controller.spec.ts
- src/modules/auth/controllers/meemoo.controller.ts
> feat(arc-415): implement meemoo idp security check

- src/shared/services/session.service.ts
> feat(session): disabled secure cookies

- .env/.env.template
- README.md
- package-lock.json
- package.json
- src/app.module.ts
- src/main.ts
- src/modules/data/services/data-permissions.service.spec.ts
- src/modules/data/services/data-permissions.service.ts
- src/modules/data/services/data.service.ts
- src/modules/spaces/controllers/spaces.controller.spec.ts
- src/modules/spaces/controllers/spaces.controller.ts
- src/modules/spaces/dto/spaces.dto.ts
- src/modules/spaces/index.ts
- src/modules/spaces/services/__mocks__/cp_space.ts
- src/modules/spaces/services/queries.gql.ts
- src/modules/spaces/services/spaces.service.spec.ts
- src/modules/spaces/services/spaces.service.ts
- src/modules/spaces/spaces.module.ts
- src/modules/spaces/types.ts
- src/modules/users/index.ts
- src/modules/users/users.module.ts
Spaces list: zoek op naam en beschrijving, incl paginering
spaces detail: query by id
Testen toegevoegd
wat consistency namings gewijzigd
readme update
> feat(arc-278) query spaces 

- .gitignore
- .prettierrc
* ignore .idea folder
* allow windows to use crlf line endings in prettier (git will always commit as lf)
> fix(gitignore): ignore idea files

- src/modules/spaces/services/queries.gql.ts
- src/modules/spaces/services/spaces.service.ts
- src/modules/spaces/types.ts
cleanup query
Nog wachten op antwoorden van comments in issue https://meemoo.atlassian.net/browse/ARC-277
> feat(arc-277): Space detail

- src/modules/media/dto/media.dto.ts
> feat(media): add swagger info for filter options for the media endpoint

- src/app.module.ts
- src/modules/media/controllers/media.controller.ts
- src/modules/spaces/controllers/spaces.controller.ts
- src/modules/spaces/services/queries.gql.ts
- src/modules/spaces/services/spaces.service.spec.ts
- src/modules/spaces/services/spaces.service.ts
- src/modules/visits/controllers/visits.controller.spec.ts
- src/modules/visits/controllers/visits.controller.ts
- src/modules/visits/dto/visits.dto.ts
- src/modules/visits/index.ts
- src/modules/visits/services/__mocks__/cp_visit.ts
- src/modules/visits/services/queries.gql.ts
- src/modules/visits/services/visits.service.spec.ts
- src/modules/visits/services/visits.service.ts
- src/modules/visits/types.ts
- src/modules/visits/visits.module.ts
- src/shared/helpers/pagination.spec.ts
- src/shared/helpers/pagination.ts
- simple get all visits with pagination
- get visit by id
- create visit
- tests added
- some consistency / swagger updates
OPM: access_remarks field not yet in DB
> feat(arc-282): add visits module

- src/modules/visits/controllers/visits.controller.ts
- src/modules/visits/dto/visits.dto.ts
- src/modules/visits/services/queries.gql.ts
- src/modules/visits/services/visits.service.spec.ts
- src/modules/visits/services/visits.service.ts
- src/modules/visits/types.ts
Added
* text search
* status filtering
* name and email of the requester
since we need those in the UI:
> feat(visits): add query option for searching + return name and email

- src/modules/media/dto/media.dto.ts
- src/modules/media/elasticsearch/queryBuilder.spec.ts
- src/modules/media/elasticsearch/queryBuilder.ts
- src/modules/spaces/dto/spaces.dto.ts
- src/modules/visits/dto/visits.dto.ts
- page: number; // one based
- size: number;
> feat(paging): make all paging and size params uniform

- src/modules/media/dto/media.dto.ts
- src/modules/media/elasticsearch/queryBuilder.ts
- src/modules/spaces/dto/spaces.dto.ts
- src/modules/spaces/services/queries.gql.ts
- src/modules/spaces/services/spaces.service.ts
- src/modules/visits/consts.ts
- src/modules/visits/dto/visits.dto.ts
- src/modules/visits/services/queries.gql.ts
- src/modules/visits/services/visits.service.ts
adds 2 properties to all getAll routes:
* orderProp
* orderDirection
> feat(arc-397): add sorting options to all getAll routes

- src/modules/tos/controllers/tos.controller.ts
- src/modules/tos/services/queries.gql.ts
- src/modules/tos/services/tos.service.spec.ts
- src/modules/tos/services/tos.service.ts
- src/modules/users/controllers/users.controller.spec.ts
- src/modules/users/services/users.service.ts
- src/modules/visits/consts.ts
- src/modules/visits/services/visits.service.ts
- src/modules/visits/types.ts
Get tos updated_at date from the site_variables table in the database
> feat(arc-168): get tos updated_at date from the database site_variables

- src/app.module.ts
- src/modules/auth/session-helper.spec.ts
- src/modules/users/controllers/users.controller.spec.ts
- src/modules/users/controllers/users.controller.ts
- src/modules/users/dto/users.dto.ts
- src/modules/users/services/queries.gql.ts
- src/modules/users/services/users.service.spec.ts
- src/modules/users/services/users.service.ts
- src/modules/users/types.ts
- src/modules/users/users.module.ts
increased test coverage
refactored userservice for consistency
add route to update user accepted tos
> feat(arc-498): add acceptedTos to user properties

- postman_collection.json
> chore(api): add postman collection

- src/modules/spaces/services/queries.gql.ts
- src/modules/spaces/services/spaces.service.spec.ts
- src/modules/spaces/services/spaces.service.ts
Changes after tech sync: added description fallback
> feat(arc-277): leeszaal description fallback

- src/modules/spaces/services/spaces.service.ts
- src/modules/visits/controllers/visits.controller.spec.ts
- src/modules/visits/controllers/visits.controller.ts
- src/modules/visits/dto/visits.dto.ts
- src/modules/visits/services/queries.gql.ts
- src/modules/visits/services/visits.service.spec.ts
- src/modules/visits/services/visits.service.ts
- src/modules/visits/types.ts
- query visits by user
http://localhost:{{port}}/visits?userProfileId={{userID}}
- query visits by space
http://localhost:{{port}}/visits?spaceId={{spaceId}}
- update status
PUT http://localhost:{{port}}/visits/{{visitID}}/status
body. { status: "APPROVED" }
- update
PUT http://localhost:{{port}}/visits/{{visitID}}/status
body. { startAt: "2022-02-18T14:00:00", endAt: "2022-02-18T16:00:00 }
> feat(arc-279): query visits by user

- src/modules/auth/controllers/het-archief.controller.spec.ts
- src/modules/auth/controllers/meemoo.controller.spec.ts
otherwise the jenkins build fails:
> fix(auth): check auth error code and message separately

- src/modules/auth/controllers/het-archief.controller.spec.ts
- src/modules/auth/controllers/meemoo.controller.spec.ts
- src/modules/media/elasticsearch/queryBuilder.spec.ts
- src/modules/tos/services/__mocks__/tos.ts
- src/modules/tos/services/queries.gql.ts
- src/modules/tos/services/tos.service.spec.ts
- src/modules/tos/services/tos.service.ts
- src/modules/tos/types.ts
- src/modules/visits/services/visits.service.spec.ts
- src/modules/visits/services/visits.service.ts
- refactored tos date implementation
- fixed test coverage
> fix(tos): refactored tos date implementation

- src/modules/media/controllers/media.controller.spec.ts
- src/modules/media/controllers/media.controller.ts
- src/modules/media/elasticsearch/queryBuilder.spec.ts
- src/modules/media/elasticsearch/queryBuilder.ts
- src/modules/media/services/__mocks__/object_ie.ts
- src/modules/media/services/media.service.spec.ts
- src/modules/media/services/media.service.ts
- src/modules/media/services/queries.gql.ts
- src/modules/media/types.ts
- src/modules/spaces/types.ts
- src/shared/types/types.ts
Retrieve all Object details from DB
Based on PR #55
> feat(arc-298): item detail from DB

- src/modules/visits/consts.ts
- src/modules/visits/controllers/visits.controller.spec.ts
- src/modules/visits/controllers/visits.controller.ts
- src/modules/visits/dto/visits.dto.ts
- src/modules/visits/services/__mocks__/cp_visit.ts
- src/modules/visits/services/queries.gql.ts
- src/modules/visits/services/visits.service.spec.ts
- src/modules/visits/services/visits.service.ts
- src/modules/visits/types.ts
- refactored acceptedAt to boolean (again)
- changed PUT methods to PATCH
> feat(arc-553): Add notes to visit requests

- jest.config.js
- jest.setup.redis-mock.ts
- package-lock.json
- package.json
- src/modules/auth/services/het-archief.service.spec.ts
- src/modules/collections/services/__mocks__/idpXmlResponse.ts
- src/modules/data/services/data.service.spec.ts
- src/modules/media/services/media.service.spec.ts
- src/shared/services/session.service.spec.ts
- src/shared/services/session.service.ts
* add tests for session service
* add mock for fetching idp xml info
```
src/shared/services                       |   86.66 |    66.66 |   57.14 |    92.5 |                            
session.service.ts                       |   86.66 |    66.66 |   57.14 |    92.5 | 30,84-85    
```
> feat(session-service): add tests for session service + mock redis

- src/modules/visits/controllers/visits.controller.spec.ts
- src/modules/visits/controllers/visits.controller.ts
* https://meemoo.atlassian.net/browse/ARC-430
* https://meemoo.atlassian.net/browse/ARC-432
Add notification when someone calls the update visit endpoint with an approved or denied status
> feat(arc-430): add notifications when a visit request is approved/denied

- src/modules/admin/navigations/dto/navigations.dto.spec.ts
- src/modules/collections/dto/collections.dto.spec.ts
- src/modules/data/dto/graphql-query.dto.spec.ts
- src/modules/media/dto/media.dto.spec.ts
- src/modules/notifications/dto/notifications.dto.spec.ts
- src/modules/notifications/services/notifications.service.spec.ts
- src/modules/spaces/dto/spaces.dto.spec.ts
- src/modules/spaces/dto/spaces.dto.ts
- src/modules/users/dto/users.dto.spec.ts
- src/modules/visits/consts.ts
- src/modules/visits/controllers/visits.controller.spec.ts
- src/modules/visits/controllers/visits.controller.ts
- src/modules/visits/dto/visits.dto.spec.ts
- src/modules/visits/dto/visits.dto.ts
- src/modules/visits/services/__mocks__/cp_visit.ts
- src/modules/visits/services/queries.gql.ts
- src/modules/visits/services/visits.service.spec.ts
- src/modules/visits/services/visits.service.ts
- src/modules/visits/types.ts
Instantiates the dto objects for each module and ests their default values.
this increases the coverage from
```
-------------------------------------------|---------|----------|---------|---------|-----------------------------
File                                       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s           
-------------------------------------------|---------|----------|---------|---------|-----------------------------
All files                                  |   78.32 |    76.31 |   75.11 |   80.05 |      
```
to
```
-------------------------------------------|---------|----------|---------|---------|-----------------------------
File                                       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s …
```
> feat(tests): add tests for dto files

- src/modules/collections/services/collections.service.spec.ts
- src/modules/notifications/controllers/notifications.controller.spec.ts
- src/modules/notifications/controllers/notifications.controller.ts
- src/modules/notifications/services/notifications.service.spec.ts
- src/modules/notifications/services/notifications.service.ts
- src/modules/notifications/services/queries.gql.ts
- src/modules/notifications/types.ts
> feat(arc-284): add mark one - and mark all notifications as read

- jest.config.js
This makes it a lot easier to identify files that we care about that still need more coverage.
We can re-enable the other files once we hit 100% and we find a good way to test the ignored files.
```
-------------------------------------------|---------|----------|---------|---------|-------------------
File                                       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-------------------------------------------|---------|----------|---------|---------|-------------------
All files                                  |   94.76 |    90.63 |   91.55 |   94.69 |                  
src                                       |   39.47 |        0 |      75 |   32.35 |                  
app.controller.ts                        |     100 |      100 |     100 | …
```
> feat(tests): ignore module, dto and barrel files from coverage

- src/modules/campaign-monitor/services/campaign-monitor.service.spec.ts
- src/modules/notifications/controllers/notifications.controller.ts
- src/modules/notifications/services/notifications.service.spec.ts
- src/modules/users/services/users.service.ts
- src/modules/visits/consts.ts
- src/modules/visits/controllers/visits.controller.spec.ts
- src/modules/visits/controllers/visits.controller.ts
- src/modules/visits/dto/visits.dto.ts
- src/modules/visits/services/queries.gql.ts
- src/modules/visits/services/visits.service.spec.ts
- src/modules/visits/services/visits.service.ts
- src/modules/visits/types.ts
> feat(arc-218): add prop spaceName to visit response + sortable

- src/modules/media/dto/media.dto.spec.ts
- src/modules/media/dto/media.dto.ts
- src/modules/media/elasticsearch/consts.ts
- src/modules/media/elasticsearch/queryBuilder.spec.ts
- src/modules/media/elasticsearch/queryBuilder.ts
- src/modules/media/elasticsearch/templates/search-query-advanced.json
- src/modules/media/services/media.service.ts
- src/modules/media/types.ts
- different free text search implementation for advanced section
- general structure: between filters === AND, inside a filter with multiValue (array): OR
> feat(arc-294): refactor to a general searchfilter structure

- src/modules/campaign-monitor/services/campaign-monitor.service.spec.ts
- src/modules/notifications/controllers/notifications.controller.spec.ts
- src/modules/notifications/services/notifications.service.spec.ts
- src/modules/visits/consts.ts
- src/modules/visits/controllers/visits.controller.spec.ts
- src/modules/visits/dto/visits.dto.ts
- src/modules/visits/services/__mocks__/cp_visit.ts
- src/modules/visits/services/queries.gql.ts
- src/modules/visits/services/visits.service.spec.ts
- src/modules/visits/services/visits.service.ts
- src/modules/visits/types.ts
Hasura better seed branch: https://github.com/viaacode/hetarchief-hasura/pull/74
> feat(arc-508): add approved by column data to visits table

- src/modules/data/services/data-permissions.service.ts
- src/modules/users/services/users.service.ts
- src/shared/guards/logged-in.guard.ts
the object can sometimes exist with only this inside:
```
{
permissions: []
}
```
> fix(logged-in-guard): add stricter check for user session object

- src/modules/media/controllers/media.controller.ts
- src/modules/media/elasticsearch/queryBuilder.spec.ts
- src/modules/media/elasticsearch/queryBuilder.ts
- src/modules/media/services/media.service.spec.ts
- src/modules/media/services/media.service.ts
- src/modules/spaces/controllers/spaces.controller.spec.ts
- src/modules/spaces/controllers/spaces.controller.ts
- src/modules/spaces/dto/spaces.dto.spec.ts
- src/modules/spaces/dto/spaces.dto.ts
- src/modules/spaces/services/queries.gql.ts
- src/modules/spaces/services/spaces.service.spec.ts
- src/modules/spaces/services/spaces.service.ts
- src/modules/spaces/types.ts
> feat(arc-392): add option to get accessible reading rooms for user

- src/generated/graphql-db-types-hetarchief.ts
- src/modules/collections/queries/find-object-by-schema-identifier.graphql
- src/modules/collections/queries/find-object-by-schema_identifier.graphql
- src/modules/collections/queries/find-object-in-collection.graphql
sync fetched object properties across queries
> fix(collections): sync fetched object properties across queries

- src/shared/auth/session-helper.ts
https://studiohyperdrive.slack.com/archives/C0279QSL9CZ/p1649776713587959
> Make permissions fallback more easily maintainable

- src/modules/media/elasticsearch/consts.ts
- src/modules/media/elasticsearch/queryBuilder.spec.ts
- src/modules/media/elasticsearch/queryBuilder.ts
- src/modules/media/types.ts
> feat(es-search): fix search on genre

- src/modules/notifications/controllers/notifications.controller.ts
> feat(arc-438): fix recurring notification

- src/generated/database-aliases.ts
- src/modules/media/controllers/media.controller.ts
- src/modules/notifications/services/notifications.service.spec.ts
- src/modules/spaces/controllers/spaces.controller.spec.ts
- src/modules/spaces/controllers/spaces.controller.ts
- src/modules/spaces/dto/spaces.dto.ts
- src/modules/spaces/services/__mocks__/cp_space.ts
- src/modules/spaces/services/spaces.service.spec.ts
- src/modules/spaces/services/spaces.service.ts
- src/modules/spaces/types.ts
- src/modules/visits/controllers/visits.controller.spec.ts
- src/modules/visits/services/__mocks__/cp_visit.ts
- update space status
- aliased lookup imports
> feat(spaces): update visitor space statuses

- src/modules/admin/navigations/services/admin-navigations.service.ts
- src/modules/media/controllers/media.controller.ts
- src/modules/visits/controllers/visits.controller.spec.ts
- src/modules/visits/dto/visits.dto.ts
- src/modules/visits/services/visits.service.ts
> chore(linting): fix linting errors

- src/modules/visits/controllers/visits.controller.spec.ts
- src/modules/visits/controllers/visits.controller.ts
- src/modules/visits/services/visits.service.spec.ts
- src/modules/visits/services/visits.service.ts
Required for client feature: https://github.com/viaacode/hetarchief-client/pull/270
> feat(arc-448): Return 404 or 403 for active space request

- src/modules/collections/controllers/collections.controller.ts
- src/modules/media/controllers/media.controller.ts
- src/modules/users/types.ts
- src/modules/visits/controllers/visits.controller.ts
- src/shared/decorators/require-permissions.decorator.ts
* Add MANAGE_ACCOUNT permission
* rename RequirePermissions to RequireAllPermissions
* rename MANAGE_COLLECTIONS to MANAGE_FOLDERS
> feat(arc-303): add MANAGE_ACCOUNT permission

- src/modules/media/controllers/media.controller.spec.ts
- src/modules/media/controllers/media.controller.ts
- src/modules/media/services/media.service.spec.ts
- src/modules/media/services/media.service.ts
Add the film aggregations to the video aggregations
> fix(arc-714): add film to video aggregations

- src/config/index.ts
- src/modules/admin/content-pages/controllers/content-pages.controller.ts
- src/modules/collections/controllers/collections.controller.ts
- src/modules/data/services/data.service.spec.ts
- src/modules/data/services/data.service.ts
- src/modules/spaces/controllers/spaces.controller.spec.ts
- src/modules/spaces/controllers/spaces.controller.ts
- src/modules/status/services/status.service.spec.ts
- src/modules/visits/controllers/visits.controller.ts
- src/modules/visits/services/visits.service.ts
- src/shared/guards/permission.guard.ts
Changed Unauthorized exception to Forbidden exception in most cases
> fix(arc-787): only throw unauthorized when user is not logged in

- src/modules/admin/content-pages/controllers/content-pages.controller.ts
- src/modules/organisations/controllers/organisations.controller.ts
> fix(swagger): add param to set api key header

- src/modules/collections/services/collections.service.ts
https://meemoo.atlassian.net/browse/ARC-933
client PR: https://github.com/viaacode/hetarchief-client/pull/462
> feat(arc-933): Search program and series inside folders

- src/modules/spaces/services/spaces.service.spec.ts
- src/modules/spaces/services/spaces.service.ts
https://meemoo.atlassian.net/browse/ARC-545
> fix(arc-545): correctly adapt telephone and email for a visitor space

- src/modules/auth/controllers/auth.controller.ts
https://meemoo.atlassian.net/browse/ARC-853
since hasura webhooks only support post methods
> fix(arc-853): make clear sessions a post instead of delete method

- src/modules/spaces/services/spaces.service.ts
https://meemoo.atlassian.net/browse/ARC-474
asc:
desc:
> feat(arc-474): sort visitor spaces by status

- src/modules/admin/player-ticket/services/player-ticket.service.ts
https://meemoo.atlassian.net/browse/ARC-974
> fix(arc-974): do not change thumbnail path if it's an absolute url

- .env/.env.template
- src/app.module.ts
- src/config/config.const.ts
- src/config/config.types.ts
- src/config/index.ts
- src/modules/client-cache/client-cache.module.ts
- src/modules/client-cache/controllers/client-cache.controller.ts
https://meemoo.atlassian.net/browse/ARC-1002
requires client PR: https://github.com/viaacode/hetarchief-client/pull/480
so we can ensure content pages are cleared after changes are made to them
> feat(arc-1002): add route to clear client cache

- src/modules/admin/content-pages/controllers/content-pages.controller.ts
- src/modules/auth/controllers/auth.controller.ts
- src/modules/campaign-monitor/controllers/campaign-monitor.controller.ts
- src/modules/client-cache/controllers/client-cache.controller.ts
- src/modules/notifications/controllers/notifications.controller.ts
- src/modules/organisations/controllers/organisations.controller.ts
- src/modules/organisations/services/organisations.service.ts
- src/shared/i18n/locales/nl.json
https://meemoo.atlassian.net/browse/ARC-900
* Fetch telephone field to put in organisation cache
* make apikey header fully lowercase to avoid issues with capitals
before:
after:
> fix(arc-900): also fetch telephone number to put in organisation cache

- src/modules/media/elasticsearch/queryBuilder.spec.ts
- src/modules/media/elasticsearch/queryBuilder.ts
- src/modules/media/elasticsearch/templates/search-query-advanced.json
- src/modules/media/elasticsearch/templates/search-query.json
https://meemoo.atlassian.net/browse/ARC-1021
> feat(arc-1021): allow search by object ids in elasticsearch

- scripts/admin-core-whitelist-avo.json
- scripts/admin-core-whitelist-hetarchief.json
admin core queries to soft delete a content page were updated
> fix(arc-1036): whitelist admin core queries

- src/modules/admin/content-pages/controllers/content-pages.controller.ts
fix(arc-1070): update logged in detection to set correct user group
> fix(arc-1070): update logged in detection to set correct user group

- src/modules/visits/controllers/visits.controller.ts
- src/modules/visits/services/visits.service.ts
Filter personal visits on active space by default
> fix(arc-1071): Filter personal visits on active space by default

- codegen-hetarchief.yml
send security header on db type generation
> feat(typegen): send security header on db type generation

- src/modules/auth/controllers/het-archief.controller.spec.ts
- src/modules/auth/controllers/het-archief.controller.ts
- src/modules/auth/controllers/meemoo.controller.spec.ts
- src/modules/auth/controllers/meemoo.controller.ts
- src/modules/auth/services/idp.service.ts
specific error message on no maintainer / or-id
tested by manually setting maintainerId to null in src/modules/auth/services/idp.service.ts L67
> feat(arc-976): error message on no maintainer

- src/modules/auth/controllers/het-archief.controller.spec.ts
- src/modules/media/__mocks__/media-object-mocks.ts
- src/modules/media/elasticsearch/templates/search-query-advanced.json
- src/modules/media/elasticsearch/templates/search-query.json
- src/modules/media/media.types.ts
- src/modules/media/queries/get-object-detail-by-schema-identifier.graphql
- src/modules/media/queries/get-related-objects.graphql
- src/modules/media/services/__mocks__/object_ie.ts
- src/modules/media/services/media.service.ts
https://meemoo.atlassian.net/browse/ARC-884
client PR: https://github.com/viaacode/hetarchief-client/pull/548
before:
after:
> fix(avo-884): remove all references to schema_contributor from media

- src/modules/media/media.types.ts
https://meemoo.atlassian.net/browse/ARC-885
> fix(arc-885): fix alternative name type for object

- src/modules/auth/controllers/het-archief.controller.ts
- src/modules/auth/controllers/meemoo.controller.ts
- src/modules/collections/controllers/collections.controller.ts
- src/modules/events/services/events.service.spec.ts
- src/modules/visits/controllers/visits.controller.ts
https://meemoo.atlassian.net/browse/ARC-774
client companion PR: https://github.com/viaacode/hetarchief-client/pull/556
> fix(arc-774): improve events according to jira remarks

- src/modules/media/elasticsearch/templates/fuzzy/search-query-advanced.json
- src/modules/media/elasticsearch/templates/fuzzy/search-query.json
https://meemoo.atlassian.net/browse/ARC-1092
before:
after:
> fix(arc-1092): fix searching in creator template for elasticsearch

- src/modules/media/elasticsearch/queryBuilder.ts
https://meemoo.atlassian.net/browse/ARC-1016
> fix(arc-1016): sort by most recent first if no filters are provided

- src/modules/media/controllers/media.controller.ts
- src/modules/media/media.types.ts
https://meemoo.atlassian.net/browse/ARC-542
> fix(arc-542): add route to fetch object title for seo without login

- src/modules/auth/constants.ts
- src/modules/auth/controllers/het-archief.controller.ts
- src/modules/auth/controllers/meemoo.controller.ts
- src/modules/auth/org-not-linked-redirect.ts
- src/modules/auth/services/idp.service.ts
https://meemoo.atlassian.net/browse/ARC-976
> fix(arc-976): ensure error is handled correctly

- src/modules/ie-objects/controllers/ie-objects.controller.ts
- src/modules/ie-objects/dto/ie-objects.dto.ts
- src/modules/ie-objects/services/ie-objects.service.ts
> feat(arc-1335): add related count for ie objects

- src/modules/material-requests/material-requests.consts.ts
> fix: fix type order prop for material requests

- src/modules/ie-objects/elasticsearch/elasticsearch.consts.ts
- src/modules/ie-objects/elasticsearch/templates/exact/identifier-search-query.json
- src/modules/ie-objects/ie-objects.types.ts
- src/modules/ie-objects/services/ie-objects.service.ts
> feat(arc-1333): adjust esobject and ie object props

- src/modules/collections/controllers/collections.controller.spec.ts
- src/modules/collections/controllers/collections.controller.ts
- src/modules/collections/types.ts
> feat(arc-1355): add share folder endpoint

- src/generated/graphql-db-types-hetarchief.ts
- src/modules/material-requests/controllers/material-requests.controller.spec.ts
- src/modules/material-requests/dto/material-requests.dto.spec.ts
- src/modules/material-requests/dto/material-requests.dto.ts
- src/modules/material-requests/material-requests.types.ts
- src/modules/material-requests/mocks/material-requests.mocks.ts
- src/modules/material-requests/queries/find-by-id-material-requests.graphql
- src/modules/material-requests/queries/find-material-requests.graphql
- src/modules/material-requests/queries/insert-material-request.graphql
- src/modules/material-requests/queries/update-material-request.graphql
- src/modules/material-requests/services/material-requests.service.spec.ts
- src/modules/material-requests/services/material-requests.service.ts
https://meemoo.atlassian.net/browse/ARC-1383
https://meemoo.atlassian.net/browse/ARC-1387
> feat(arc-1383): add extra fields + adjust logic accordingly

- src/generated/graphql-db-types-hetarchief.ts
- src/modules/material-requests/controllers/material-requests.controller.spec.ts
- src/modules/material-requests/controllers/material-requests.controller.ts
- src/modules/material-requests/material-requests.types.ts
- src/modules/material-requests/mocks/material-requests.mocks.ts
- src/modules/material-requests/queries/find-maintainers-with-material-requests.graphql
- src/modules/material-requests/services/material-requests.service.spec.ts
- src/modules/material-requests/services/material-requests.service.ts
Remark: Use branch `feat/ARC-1388` on repo `hetarchief-hasura` to test this out locally
> feat(arc-1388): add maintainers endpoint + write tests

- src/modules/material-requests/dto/material-requests.dto.ts
- src/modules/material-requests/services/material-requests.service.ts
> feat(arc-1390): search query in full name reversed + change types

- src/modules/collections/controllers/collections.controller.ts
- src/modules/ie-objects/services/ie-objects.service.ts
> feat(arc-1410): add default metadata for objects in folders

- src/modules/ie-objects/controllers/ie-objects.controller.ts
- src/modules/ie-objects/helpers/limit-access-to-object-details.spec.ts
- src/modules/ie-objects/helpers/limit-access-to-object-details.ts
- src/modules/ie-objects/services/ie-objects.service.ts
**Jira**
https://meemoo.atlassian.net/browse/ARC-1451
> fix(arc-1451): fix issue with licenses by user group

- src/modules/organisations/organisations.types.ts
- src/modules/organisations/services/organisations.service.ts
**JIRA**
https://meemoo.atlassian.net/browse/ARC-1437
**Remark**
Use branch `feat/ARC-1435` from the `hetarchief-hasura` repo to check this feature out
> feat(arc-1437): add form url to update cache endpoint for organisations

- src/modules/ie-objects/controllers/ie-objects.controller.ts
- src/modules/ie-objects/elasticsearch/queryBuilder.spec.ts
- src/modules/ie-objects/elasticsearch/queryBuilder.ts
- src/modules/ie-objects/helpers/limit-access-to-object-details.spec.ts
- src/modules/ie-objects/helpers/limit-access-to-object-details.ts
- src/modules/ie-objects/helpers/limit-access-to-object-details.types.ts
- src/modules/ie-objects/ie-objects.conts.ts
- src/modules/ie-objects/services/ie-objects.service.ts
* null values returned from the POST /ie-objects call, which should never happen:
* I added a test for this:
* anonymous user being able to see the essence, which should not happen without the VIAA-PUBLIEK-CONTENT license
> fix issues with object limiting, null values returned from ie-objects post call

- src/modules/auth/controllers/het-archief.controller.ts
- src/modules/auth/services/idp.service.spec.ts
- src/modules/auth/services/idp.service.ts
**Jira**
https://meemoo.atlassian.net/browse/ARC-1503
> feat(arc-1503): adjust cp admin determine user group logic

- src/modules/material-requests/controllers/material-requests.controller.ts
- src/modules/material-requests/material-requests.types.ts
- src/modules/material-requests/services/material-requests.service.ts
**Jira**
https://meemoo.atlassian.net/browse/ARC-1472
> feat(arc-1472): add meemoo group check and add user maintainer

- src/modules/material-requests/dto/material-requests.dto.ts
https://meemoo.atlassian.net/browse/ARC-1535
> fix(arc-1535): change return of isPending in dto

- src/modules/material-requests/controllers/material-requests.controller.ts
- src/modules/material-requests/services/material-requests.service.ts
https://meemoo.atlassian.net/browse/ARC-1540
> fix(arc-1540): add promise to foreach

- src/modules/campaign-monitor/services/campaign-monitor.service.ts
**Jira**
https://meemoo.atlassian.net/browse/ARC-1553
> fix(arc-1553): add logic for REROUTE EMAILS TO

- package.json
- src/modules/ie-objects/elasticsearch/elasticsearch.consts.ts
https://meemoo.atlassian.net/browse/ARC-1510
> fix(arc-1510): do not add keyword for maintainer id filter

- package.json
- src/modules/ie-objects/elasticsearch/elasticsearch.consts.ts
https://meemoo.atlassian.net/browse/ARC-1510
> feat(arc-1510): add filter to search by maintainer name

- src/modules/ie-objects/elasticsearch/elasticsearch.consts.ts
- src/modules/ie-objects/elasticsearch/queryBuilder.spec.ts
- src/modules/ie-objects/elasticsearch/queryBuilder.ts
- src/modules/ie-objects/services/ie-objects.service.ts
**Jira**
https://meemoo.atlassian.net/browse/ARC-1562
**Remark**
Tested with **ARC-1141** from `hetarchief-client`. Below are some screenshots for the results.
> fix(arc-1562): move isConsultable filters to filter array

- src/modules/spaces/controllers/spaces.controller.spec.ts
- src/modules/spaces/controllers/spaces.controller.ts
https://meemoo.atlassian.net/browse/ARC-1552
> feat(arc-1552): return http 410 for inactive spaces

- src/modules/spaces/controllers/spaces.controller.ts
- src/modules/visits/controllers/visits.controller.ts
**Jira**
https://meemoo.atlassian.net/browse/ARC-1550
**Remark**
FE should hide purple block cause is not representative for meemoo admin
> feat(arc-1550): adjust spaces logic for admin

- src/modules/ie-objects/controllers/ie-objects.controller.ts
- src/modules/ie-objects/ie-objects.types.ts
https://meemoo.atlassian.net/browse/ARC-1548
> feat(arc-1548): add description to seo call

- src/modules/ie-objects/controllers/ie-objects.controller.ts
https://meemoo.atlassian.net/browse/ARC-1591
User without access:
Meemoo admin:
> fix(arc-1591): fix accessthrough for meemoo admin

- src/modules/ie-objects/controllers/ie-objects.controller.spec.ts
- src/modules/ie-objects/mocks/ie-objects.mock.ts
- src/modules/ie-objects/services/ie-objects.service.spec.ts
- src/modules/ie-objects/services/ie-objects.service.ts
https://meemoo.atlassian.net/browse/ARC-1606
> fix(arc-1606): Fix failing tests

- src/modules/content-partners/controllers/content-partners.controller.ts
- src/modules/content-partners/dto/content-partners.dto.spec.ts
- src/modules/content-partners/dto/content-partners.dto.ts
- src/modules/content-partners/services/content-partners.service.ts
- src/modules/ie-objects/elasticsearch/elasticsearch.consts.ts
- src/modules/ie-objects/elasticsearch/queryBuilder.spec.ts
https://meemoo.atlassian.net/browse/ARC-1510
Needed for client PR: https://github.com/viaacode/hetarchief-client/pull/796
* Extend the content partner endpoint to also accept orIds query param
> feat(arc-1510): fix filtering for maintainer filter

- src/modules/ie-objects/controllers/ie-objects.controller.ts
- src/modules/ie-objects/services/ie-objects.service.ts
https://meemoo.atlassian.net/browse/ARC-1283
> fix(arc-1283): return similar objects from all maintainers if no or-id

- src/modules/material-requests/controllers/material-requests.controller.ts
- src/modules/material-requests/dto/material-requests.dto.ts
- src/modules/material-requests/material-requests.types.ts
https://meemoo.atlassian.net/browse/ARC-1633
Corresponding FE: https://github.com/viaacode/hetarchief-client/pull/824
> fix(arc-1633): fix isPending transform and contact mail

- src/modules/ie-objects/elasticsearch/queryBuilder.ts
https://meemoo.atlassian.net/browse/ARC-1647
> fix(arc-1647): fix es query for key user

- src/modules/ie-objects/elasticsearch/elasticsearch.consts.ts
- src/modules/ie-objects/elasticsearch/queryBuilder.ts
- src/modules/ie-objects/helpers/convert-node-to-es-query-filter-objects.ts
- src/modules/ie-objects/helpers/convert-string-to-search-terms.ts
- src/modules/ie-objects/helpers/encode-search-term.spec.ts
- src/modules/ie-objects/helpers/encode-search-term.ts
https://meemoo.atlassian.net/browse/ARC-1651
Note: the pid in the ticket '3r0pr9jj7g' doesn't seem to exist in ES.
Before:
After:
> fix(arc-1651): fix searching for terms starting with digit

- src/modules/material-requests/material-requests.consts.ts
- src/modules/material-requests/material-requests.types.ts
https://meemoo.atlassian.net/browse/ARC-1671
Please test with FE PR: https://github.com/viaacode/hetarchief-client/pull/863
> fix(arc-1671): add missing materialRequestOrderProps

- src/modules/ie-objects/controllers/ie-objects.controller.ts
https://meemoo.atlassian.net/browse/ARC-1787
client PR: https://github.com/viaacode/hetarchief-client/pull/940
> fix(arc-1787): only set accessThrough visitor space if space exist

- src/modules/ie-objects/controllers/ie-objects.controller.ts
- src/modules/ie-objects/elasticsearch/elasticsearch.consts.ts
- src/modules/ie-objects/elasticsearch/queryBuilder.ts
- src/modules/ie-objects/services/ie-objects.service.spec.ts
- src/modules/ie-objects/services/ie-objects.service.ts
https://meemoo.atlassian.net/browse/ARC-1283
test page while connected to QAS: http://localhost:3200/zoeken/amsab-isg/753bd083cacf4d39af7c0d9924893cc280f929288edc49e3b9702363b22ff19ee61df3f28c344bcd988bd961273470e7/kunstencentrum-vooruit-diamanda-galas-tape-2-september-1999
before:
after:
> fix(arc-1283): tweak similar query so it returns more objects

- src/modules/ie-objects/helpers/get-access-through.spec.ts
- src/modules/ie-objects/helpers/get-access-through.ts
- src/modules/ie-objects/helpers/limit-access-to-object-details.spec.ts
- src/modules/ie-objects/helpers/limit-access-to-object-details.ts
https://meemoo.atlassian.net/browse/ARC-1776
test user: hetarchief2.0+autsleutelregionale@meemoo.be
before:
after:
> fix(arc-1776): fix license checking issues with key user rights

- src/modules/ie-objects/elasticsearch/templates/exact/identifier-search-query.json
- src/modules/ie-objects/elasticsearch/templates/exact/search-query.json
- src/modules/ie-objects/elasticsearch/templates/fuzzy/search-query-advanced.json
- src/modules/ie-objects/elasticsearch/templates/fuzzy/search-query.json
https://meemoo.atlassian.net/browse/ARC-1779
before:
after:
> fix(arc-1779): add maintainer name to main search query fields

- src/modules/sitemap/controllers/sitemap.controller.spec.ts
- src/modules/sitemap/controllers/sitemap.controller.ts
- src/modules/sitemap/sitemap.module.ts
https://meemoo.atlassian.net/browse/ARC-1560
> fix(arc-1560): check api key for regenerate sitemap endpoint

- src/modules/collections/controllers/collections.controller.spec.ts
- src/modules/collections/controllers/collections.controller.ts
- src/modules/ie-objects/mocks/ie-objects.mock.ts
- src/modules/ie-objects/services/ie-objects.service.spec.ts
- src/modules/ie-objects/services/ie-objects.service.ts
- src/modules/material-requests/controllers/material-requests.controller.ts
https://meemoo.atlassian.net/browse/ARC-1800
example:
> fix(arc-1800): add extra info for several events

- src/modules/campaign-monitor/controllers/campaign-monitor.controller.spec.ts
- src/modules/campaign-monitor/controllers/campaign-monitor.controller.ts
https://meemoo.atlassian.net/browse/ARC-1801
> fix(arc-1801): fix event for anonymous newsletter subscribe

- src/modules/ie-objects/elasticsearch/elasticsearch.consts.ts
- src/modules/ie-objects/elasticsearch/queryBuilder.spec.ts
- src/modules/ie-objects/elasticsearch/queryBuilder.ts
- src/modules/ie-objects/services/ie-objects.service.ts
https://meemoo.atlassian.net/browse/ARC-1213
fix various filters that had too many or not enough results
look at the last comment to see an overview:
https://meemoo.atlassian.net/browse/ARC-1213?focusedCommentId=41740
> fix(arc-1213): fix issues with advanced filters

- src/modules/material-requests/controllers/material-requests.controller.ts
https://meemoo.atlassian.net/browse/ARC-1817
```
{
"idp": "MEEMOO",
"type": "video",
"external_id": "qszk55gn6x",
"fragment_id": "53cc83a7d87b44d0b46f4fe07df5f8310f03c1154d374d2e906b8b4b908bef8f8862447006184c8a8b44977c397dca27",
"contact_form": {
"cp_id": "OR-7h1dk9t",
"user_type": "OTHER",
"local_cp_id": "1636040",
"problem_category": "REUSE",
"problem_description": "dit is een reden van de aanvraag"
},
"user_group_id": "0b281484-76cd-45a9-b6ce-68a0ea7f4b26",
"user_group_name": "MEEMOO_ADMIN",
"material_request_group_id": "2a6afc84-b4e9-4661-a83c-30df326db865"
}
```
> fix(arc-1817): set userId as subject & add group id to material req evts

- src/modules/campaign-monitor/mocks/campaign-monitor.mocks.ts
- src/modules/campaign-monitor/services/campaign-monitor.service.spec.ts
- src/modules/ie-objects/elasticsearch/elasticsearch.consts.ts
- src/modules/ie-objects/elasticsearch/queryBuilder.ts
https://meemoo.atlassian.net/browse/ARC-1092
client PR: https://github.com/viaacode/hetarchief-client/pull/986
> fix(arc-1092): fix creator and publisher filters so they return results

- src/modules/ie-objects/elasticsearch/elasticsearch.consts.ts
- src/modules/ie-objects/services/ie-objects.service.ts
https://meemoo.atlassian.net/browse/ARC-1291
client PR: https://github.com/viaacode/hetarchief-client/pull/996
> fix(arc-1291): limit results pagination to 10000

- src/modules/collections/controllers/collections.controller.ts
Ticket: https://meemoo.atlassian.net/browse/ARC-1834
> fix(arc-1834): do not show object with license if no keyuser

- src/modules/campaign-monitor/templates/README.md
- src/modules/campaign-monitor/templates/prd/prd_arc_request item cp.html
- src/modules/campaign-monitor/templates/prd/prd_arc_request item user.html
Request item prd templates
Deze hoeven niet gedeployed te worden, ze staan hier gewoon als backup.
> add prd templates

- src/modules/ie-objects/elasticsearch/queryBuilder.ts
https://meemoo.atlassian.net/browse/ARC-1848
example on prd:
http://localhost:3200/zoeken?aanbieders=OR-7h1dk9t---Vlaams%20Parlement&created=caeq1516057200000--1516143599999&format=all&orderDirection=desc&orderProp=relevance&page=1&zoekterm=Spraakmakers%20Kathleen&zoekterm=Vlaamsparlement.tv
before:
after:
> fix(arc-1848): search multiple search terms as separate strings

- src/modules/collections/controllers/collections.controller.ts
- src/modules/ie-objects/controllers/ie-objects.controller.ts
- src/modules/ie-objects/elasticsearch/queryBuilder.spec.ts
- src/modules/material-requests/controllers/material-requests.controller.ts
- src/modules/visits/controllers/visits.controller.ts
https://meemoo.atlassian.net/browse/ARC-1883
client PR: https://github.com/viaacode/hetarchief-client/pull/1030
> feat(arc-1883): add or_id to events that deal with objects or visits

- package-lock.json
- package.json
- src/modules/collections/controllers/collections.controller.ts
https://meemoo.atlassian.net/browse/ARC-1962
requires admin-core pr: https://github.com/viaacode/react-admin-core-module/pull/207
> feat(arc-1962): add sharp library for image conversions

- src/modules/auth/controllers/het-archief.controller.ts
- src/modules/users/services/users.service.ts
https://meemoo.atlassian.net/browse/ARC-2006
> fix(ARC-2006): store organisation id in the hetarchief database on login

- src/modules/campaign-monitor/controllers/campaign-monitor.controller.ts
- src/modules/campaign-monitor/services/campaign-monitor.service.ts
https://meemoo.atlassian.net/browse/ARC-2015
> fix(ARC-2015): fix preferences call to Campaign monitor

- src/modules/ie-objects/services/ie-objects.service.ts
https://meemoo.atlassian.net/browse/ARC-2021
> fix(ARC-2021): return maintainerSlug for inaccessible objects in folder

- src/modules/material-requests/dto/material-requests.dto.ts
https://meemoo.atlassian.net/browse/ARC-2020
> fix(ARC-2020): allow reason to be empty in material request patch call

- src/modules/events/controllers/events.controller.ts
- src/modules/events/data/crawler-user-agents.json
- src/modules/events/types.ts
https://meemoo.atlassian.net/browse/ARC-2040
request met user agents that are in the bot list, are ignored
other requests are still creating events
> feat(ARC-2040): ignore events generated by bots and crawlers

- src/modules/ie-objects/services/ie-objects.service.ts
https://meemoo.atlassian.net/browse/ARC-1283
search in all material:
http://es-int-hetarchief.private.cloud.meemoo.be/or-*/_search
```json
{
"size": 4,
"from": 0,
"query": {
"bool": {
"should": [
{
"more_like_this": {
"fields": [
"schema_name",
"schema_description",
"schema_keywords.keyword",
"schema_is_part_of.*.keyword",
"schema_creator_text"
],
"like": [
{
"_index": "OR-rf5kf25",
"_id": "09f17b37445c4ce59f645c2d5db9dbf8dbee79eba623459caa8c6496108641a0900618cb6ceb4e9b8ad907e47b980ee3"
}
],
"min_term_freq": 2,
"min_doc_freq": 2,
"max_doc_freq": 6,
"max_query_terms": 12,
"min_word_length": 4
}
}
],
"minimum_should_match": 1
}
}
}
```
search in visitor spaces only:
http://es-int-hetarchief.private.cloud.meemoo.be/or-rf5kf25/_search
```json
{
"size": 4,
"from": 0,
"query": {
"bool": { …
```
> feat(ARC-1283): tweak similar to elasticsearch query

- package-lock.json
- package.json
- src/modules/auth/controllers/het-archief.controller.ts
- src/modules/auth/controllers/meemoo.controller.ts
- src/modules/auth/services/idp.service.ts
- src/modules/campaign-monitor/services/campaign-monitor.service.ts
- src/modules/client-cache/controllers/client-cache.controller.ts
- src/modules/not-found/controllers/not-found.controller.ts
- src/modules/notifications/controllers/notifications.controller.ts
- src/modules/notifications/services/notifications.service.ts
- src/modules/sitemap/mocks/sitemap.mocks.ts
- src/modules/spaces/controllers/spaces.controller.ts
- src/modules/spaces/services/spaces.service.ts
- src/modules/visits/controllers/visits.controller.ts
- src/shared/helpers/mockTranslationsService.ts
requires admin-core pr: https://github.com/viaacode/react-admin-core-module/pull/240
> feat(multi-langue-content-pages): change translate func tText

- package-lock.json
- package.json
merge together with https://github.com/viaacode/hetarchief-client/pull/1129
> feat(ARC-2076): bump admin-core to use lowercase language codes

- src/generated/graphql-db-types-hetarchief.ts
- src/modules/organisations/organisations.types.ts
- src/modules/organisations/queries/hetarchief/getOrganisationsThatHaveObjects.graphql
- src/modules/organisations/services/organisations.service.ts
https://meemoo.atlassian.net/browse/ARC-2139
requires hasura PR: https://github.com/viaacode/hetarchief-hasura/pull/261
> feat(ARC-2139): only show maintainers that have at least one object

- package-lock.json
- package.json
- src/modules/newspapers/controllers/newspapers.controller.ts
https://meemoo.atlassian.net/browse/ARC-2057
https://github.com/user-attachments/assets/acc3f347-36e7-420a-ac9f-8a7e691bc50d
> feat(ARC-2057): create endpoint to download selection of newspaper img

- src/modules/auth/controllers/het-archief.controller.ts
https://meemoo.atlassian.net/browse/ARC-2124
I think this is a bug in NestJS: https://github.com/nestjs/nest/issues/13842
but i found a workaround
> fix(ARC-2124): change redirect to be GET call to client instead of POST

- src/modules/ie-objects/elasticsearch/queryBuilder.ts
https://meemoo.atlassian.net/browse/ARC-1844
> fix(ARC-1844): add case insensitive option to search creator/publisher

- src/generated/graphql-db-types-hetarchief.ts
- src/modules/ie-objects/ie-objects.types.ts
- src/modules/ie-objects/mocks/ie-objects.mock.ts
- src/modules/ie-objects/queries/GetObjectDetailBySchemaIdentifiers.graphql
- src/modules/ie-objects/services/ie-objects.service.ts
https://meemoo.atlassian.net/browse/ARC-2419
> feat(ARC-2419): expose transcript url for newspapers (wip)

- src/modules/ie-objects/elasticsearch/elasticsearch.consts.ts
- src/modules/ie-objects/elasticsearch/queryBuilder.ts
https://meemoo.atlassian.net/browse/ARC-2206
client PR:
> feat(ARC-2206): add public domain filter to elasticsearch endpoint

- src/modules/ie-objects/elasticsearch/elasticsearch.consts.ts
- src/modules/ie-objects/elasticsearch/queryBuilder.ts
https://meemoo.atlassian.net/issues/ARC-2208
client PR: https://github.com/viaacode/hetarchief-client/pull/1207
> feat(ARC-2208): add filter release date, move other filters under advan

- src/modules/ie-objects/controllers/ie-objects.controller.ts
- src/modules/ie-objects/ie-objects.conts.ts
- src/modules/ie-objects/ie-objects.types.ts
- src/modules/ie-objects/services/ie-objects.service.ts
https://meemoo.atlassian.net/browse/ARC-2170
> feat(ARC-2170): add autocomplete metadata fields endpoint

- package-lock.json
- package.json
- src/generated/graphql-db-types-hetarchief.ts
https://meemoo.atlassian.net/browse/ARC-2264
This has been replaced by the users.profile.organisation_schema_identifier column
database PR: https://github.com/viaacode/hetarchief-hasura/pull/310
> feat(ARC-2264): remove maintainers users profile table

- src/modules/ie-objects/ie-objects.conts.ts
- src/modules/ie-objects/ie-objects.types.ts
- src/modules/ie-objects/services/ie-objects.service.ts
https://meemoo.atlassian.net/browse/ARC-2173
> feat(ARC-2173): change autocomplete use contains instead of starts with
